name: PR Storybook Preview

on:
  pull_request:
    branches: [master]

jobs:
  build_storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: diplodoc-platform/setup-node-action@00e5cddb6b6eb5f5bc02d371fa70ce645f8f5554 # v1
        with:
          node-version: ${{ vars.NODE_VERSION || '24' }}
      - name: Build Files
        run: npm run build
      - name: Build Storybook
        run: npm run storybook:build
      - name: Upload Storybook Static
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: ./storybook-static
          retention-days: 1
      - name: Save PR ID
        if: always()
        run: |
          pr="${{ github.event.pull_request.number }}"
          echo $pr > ./pr-id.txt
        shell: bash
      - name: Create PR Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt
